/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import ManagedBeans.Database;
import ManagedBeans.ManagedOrder;
import ManagedBeans.ManagedSample;
import ManagedBeans.TypeEchData;
import beans.Animals;
import beans.Orders;
import beans.Samples;
import java.awt.GridLayout;
import java.sql.Array;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;

/**
 *
 * @author Michel de la Fonchais
 */
public class CreateOrder_selectTypeEch extends javax.swing.JPanel {

    private TypeEchData typ;
    public int id_type_ech;
    private List<Integer> ListeIdAnimal = new ArrayList<Integer>();
    private List<Samples> ListeEch = new ArrayList<Samples>();
    private  Orders order;
    
    /**
     * Creates new form CreateOrder_selectTypeEch
     */
    public CreateOrder_selectTypeEch(List<Integer> ListeAnimal) {
        ListeIdAnimal=ListeAnimal;
        typ = new TypeEchData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Liste_Type = typ.getJlistTypeEchantillon();
        jButton_Add_Sample = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Sélectionner le type d'échantillon :");

        jScrollPane1.setViewportView(Liste_Type);

        jButton_Add_Sample.setBackground(new java.awt.Color(51, 102, 255));
        jButton_Add_Sample.setText("Valider");
        jButton_Add_Sample.addActionListener(new java.awt.event.ActionListener() {
            
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton_Add_SampleActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(CreateOrder_selectTypeEch.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton_Add_Sample, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton_Add_Sample)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jButton_Add_SampleActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                                   
        Samples sample = new Samples();
        String type = (String)Liste_Type.getSelectedValue();
        Animals animal = new Animals();
        
        if (type != null){
           
            Database instance = new Database();
            ManagedSample Ms = new ManagedSample();
            
            id_type_ech=instance.getIdTypeEchbyName(type);
            for(int i=0;i<ListeIdAnimal.size();i++){
                animal.setID(ListeIdAnimal.get(i));
                sample = new Samples(type, new Date(), null, animal);
                ListeEch.add(sample);
            }
            order = new Orders(ListeEch, new Date(), 0);
            ManagedOrder Mo= new ManagedOrder();
            Mo.saveOrder(order);
            
           
            
            
        }
        else {
            JOptionPane.showMessageDialog(this,"Erreur de sélection","Erreur",JOptionPane.ERROR_MESSAGE);
            id_type_ech=0;
        }
    }                                                  


    // Variables declaration - do not modify                     
    private javax.swing.JList Liste_Type;
    private javax.swing.JButton jButton_Add_Sample;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   

//        public static void main(String[] args) throws SQLException {
//        JFrame myFrame = new JFrame("Test interface Type Echantillon");
//        CreateOrder_selectTypeEch ajouterTypeEch = new CreateOrder_selectTypeEch();
//        myFrame.setLayout(new GridLayout(1, 2));
//        myFrame.add(ajouterTypeEch);
//        myFrame.pack();
//        myFrame.setVisible(true);
//        myFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);
//    }
}
